<a href="https://colab.research.google.com/github/Pritush09/Deep-Learning-Tensorflow/blob/master/Tensorflow_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [5]:
tensor_0_d = tf.constant(4)
print(tensor_0_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_1d = tf.constant([2,3])
print(tensor_1d)

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [8]:
tensor_2d = tf.constant([[2,3],[2,3]])
print(tensor_2d)

tf.Tensor(
[[2 3]
 [2 3]], shape=(2, 2), dtype=int32)


In [10]:
tensor_3d = tf.constant([
                          [[2,3],[2,3]],
                          [[1,2],[1,2]]
                        ])
print(tensor_3d)

tf.Tensor(
[[[2 3]
  [2 3]]

 [[1 2]
  [1 2]]], shape=(2, 2, 2), dtype=int32)


In [14]:
# numpy array to tensor
import numpy as np

np_arr = np.array([[1,2,3],[1,2,3]],dtype=np.float32)

np_to_tf = tf.convert_to_tensor(np_arr)
print(np_to_tf)

tf.Tensor(
[[1. 2. 3.]
 [1. 2. 3.]], shape=(2, 3), dtype=float32)


In [21]:
# eye tensor
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=[5,3],
    dtype=tf.dtypes.float32,
    name=None
)
eye_tensor

<tf.Tensor: shape=(5, 3, 3, 4), dtype=float32, numpy=
array([[[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]]],


       [[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]]],


       [[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]]],


       [[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
