<a href="https://colab.research.google.com/github/Pritush09/Deep-Learning-Tensorflow/blob/master/Tensorflow_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_0_d = tf.constant(4)
print(tensor_0_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_1d = tf.constant([2,3])
print(tensor_1d)

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [4]:
tensor_2d = tf.constant([[2,3],[2,3]])
print(tensor_2d)

tf.Tensor(
[[2 3]
 [2 3]], shape=(2, 2), dtype=int32)


In [5]:
tensor_3d = tf.constant([
                          [[2,3],[2,3]],
                          [[1,2],[1,2]]
                        ])
print(tensor_3d)

tf.Tensor(
[[[2 3]
  [2 3]]

 [[1 2]
  [1 2]]], shape=(2, 2, 2), dtype=int32)


In [6]:
# numpy array to tensor
import numpy as np

np_arr = np.array([[1,2,3],[1,2,3]],dtype=np.float32)

np_to_tf = tf.convert_to_tensor(np_arr)
print(np_to_tf)

tf.Tensor(
[[1. 2. 3.]
 [1. 2. 3.]], shape=(2, 3), dtype=float32)


In [7]:
# eye tensor
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=[2,3],
    dtype=tf.dtypes.float32,
    name=None
)
eye_tensor

<tf.Tensor: shape=(2, 3, 3, 4), dtype=float32, numpy=
array([[[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]]],


       [[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]],

        [[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]]]], dtype=float32)>

In [8]:
# fill method
fill = tf.fill(dims=(3,3,3),value=9)
fill

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]], dtype=int32)>

In [9]:
# ones like
one_like = tf.ones_like(input=fill)
one_like

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)>

In [10]:
tf.rank(fill)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [11]:
tf.size(fill)

<tf.Tensor: shape=(), dtype=int32, numpy=27>

In [12]:
# random.normal
# the values are drawn from a normal distribution

radm = tf.random.normal(shape=[3,3])
radm

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7964333,  0.9653943,  1.3786125],
       [-1.2165933,  1.1537163, -1.3063504],
       [-2.529955 ,  0.5531042,  1.20201  ]], dtype=float32)>

# for maths
https://www.tensorflow.org/api_docs/python/tf/math